### 1. 创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [1]:
import numpy as np
a=np.zeros(10)
print((a))
a[4]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. 请分别按一下两种方式各创建一个以10起始，以49结束的等差序列ndarray对象
2.1 包含20个元素  
2.2 每隔3取值一个元素

In [2]:
#2 从10到49的ndarray对象
a=np.arange(10,50)
print(a)
#2.1 包含20个元素的ndarray对象
b=np.linspace(10,49,20)
print(b)
#2.2 每隔3取值一个元素
c=np.arange(10,50,3)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10.         12.05263158 14.10526316 16.15789474 18.21052632 20.26315789
 22.31578947 24.36842105 26.42105263 28.47368421 30.52631579 32.57894737
 34.63157895 36.68421053 38.73684211 40.78947368 42.84210526 44.89473684
 46.94736842 49.        ]
[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


### 3. 将2中最后一个ndarray翻转

In [3]:
reverse=c[::-1]
print(reverse)

[49 46 43 40 37 34 31 28 25 22 19 16 13 10]


### 4. 使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [4]:
d=np.random.random((10,10))
print(d)
print(d.max())
print(d.min())

[[0.27147476 0.27661092 0.35028677 0.40503657 0.00847926 0.02301072
  0.33543466 0.64025414 0.43770876 0.50147972]
 [0.71953625 0.23245661 0.49361228 0.62449255 0.91741456 0.2034042
  0.95825408 0.29064619 0.22791075 0.59673789]
 [0.74724411 0.84842126 0.36160582 0.43907599 0.18914936 0.80027085
  0.93697432 0.82863635 0.408509   0.25591964]
 [0.7725199  0.3538933  0.49395056 0.47608757 0.48635117 0.79620367
  0.0338292  0.17414863 0.17423225 0.82889288]
 [0.31096335 0.35138826 0.26526758 0.41335717 0.31588318 0.67130923
  0.66225784 0.16191305 0.55080473 0.35999907]
 [0.66057452 0.58709749 0.77794409 0.89520305 0.27971749 0.44516037
  0.08485201 0.99333145 0.11348546 0.36594797]
 [0.46198576 0.59496018 0.40563449 0.94793268 0.99174283 0.67504337
  0.53141862 0.18688285 0.19511739 0.13018923]
 [0.36648469 0.54661881 0.28664554 0.41995044 0.053262   0.5318881
  0.84653257 0.95368445 0.12651468 0.89270178]
 [0.06688837 0.70602769 0.90792855 0.79511611 0.94063397 0.2146365
  0.19969439 0.

### 5. 创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [5]:
e=np.zeros((10,10))
e[[0,9]]=1
e[:,[0,9]]=1
print(e)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 6. 创建一个每一行都是从0到4的5*5矩阵

In [6]:
f=np.array([0,1,2,3,4]*5).reshape(5,5)
#f=np.repeat([[0,1,2,3,4]],5,axis=0)
print(f)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 7. 创建一个长度为10的随机数组并将最大值替换为0

In [7]:
g=np.random.randint(0,100,10)
print(g)
gmax=g.max()
gmaxwhere=g==gmax #g==max returns an ndarray containing true, false, ...(only one "true" when it indexes the max value.)
g[gmaxwhere]=0
print(g)

[86 12 50 82  7 81 25 21 22 12]
[ 0 12 50 82  7 81 25 21 22 12]


### 8. 生成长度为10的随机数组m
8.1 运行print(t.argsort())  
8.2 运行t.sort()  
比较两个排序命令的区别

In [8]:
m=np.random.randint(0,100,10)
print(m)
#8.1
print(m.argsort())
#8.2
m.sort()
print(m)

#区别：print(t.argsort())将数组按从小到大排列，并按照对应的索引值输出；sort()在原数组上进行从小到大的重新排序。

[26 22 91  0 41 55  9 51 89 31]
[3 6 1 0 9 4 7 5 8 2]
[ 0  9 22 26 31 41 51 55 89 91]


### 9. 给定一个4维矩阵，如何得到最后两维的和？
可使用np.random.randint(0,10,(3,3,3,3))生成0到9范围内的随机整数矩阵

In [9]:
h=np.random.randint(0,10,(3,3,3,3))
j=h.sum(axis=(-1,-2))
print(j)

[[55 48 39]
 [31 38 27]
 [45 42 51]]


### 10. 给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [10]:
o=np.arange(1,6)
p=np.zeros(17,dtype=np.int8)
p[::4]=o
print(p)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


### 11. 给定一个二维矩阵，如何交换其中两行的元素？

In [11]:
q=np.random.randint(0,100,(3,3))
print(q)
print(q[[1,0,2]])

[[32 72  8]
 [ 0 87 78]
 [36  7 12]]
[[ 0 87 78]
 [32 72  8]
 [36  7 12]]


### 12. 创建一个5 \* 3 随机矩阵和一个3 \* 2随机矩阵，求矩阵积

In [12]:
r=np.random.randint(0,10,(5,3))
s=np.random.randint(0,10,(3,2))
product=np.dot(r,s)
print(r)
print(s)
print(product)

[[7 5 9]
 [5 6 5]
 [8 5 5]
 [6 6 4]
 [9 8 6]]
[[1 9]
 [8 5]
 [7 7]]
[[110 151]
 [ 88 110]
 [ 83 132]
 [ 82 112]
 [115 163]]


### 13. 生成一个5 \*5 的0到10之间的随机整数矩阵，矩阵的每一行的元素都减去该行的平均值

In [13]:
u=np.random.randint(0,11,(5,5))
print(u)
average=u.mean(axis=1).reshape(5,1)
print(average)
u=u-average 
print(u)

[[ 0  9 10  7  6]
 [ 4  1  9  4  2]
 [ 8  9  0  7 10]
 [ 1  8  3  6  2]
 [10  5  0  2  0]]
[[6.4]
 [4. ]
 [6.8]
 [4. ]
 [3.4]]
[[-6.4  2.6  3.6  0.6 -0.4]
 [ 0.  -3.   5.   0.  -2. ]
 [ 1.2  2.2 -6.8  0.2  3.2]
 [-3.   4.  -1.   2.  -2. ]
 [ 6.6  1.6 -3.4 -1.4 -3.4]]


### 14. 生成如下矩阵：
[[0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 [0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 [0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 [0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]]  
 14.1 要求使用np.zeros创建8*8的矩阵  
 14.2 np.fromfunction创建

In [14]:
#14.1
v=np.zeros((8,8),dtype=np.int8)
v[::2,1::2]=1
v[1::2,::2]=1
print(v)

#14.2
def fun(x,y):
    return((x+y)%2)
w=np.fromfunction(fun,(8,8),dtype=np.int8)
print(w)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 15、正则化一个5\*5随机矩阵  
【正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)】

In [15]:
z=np.random.randint(0,100,size=(5,5))
print(z)
zmin=z.min()
zmax=z.max()
z=(z-zmin)/(zmax-zmin)
print(z)

[[60  3 84 54 99]
 [ 4 47 37 38 49]
 [23 59 71 71 76]
 [72 78 46 61 67]
 [39 81 68 37 59]]
[[0.59375    0.         0.84375    0.53125    1.        ]
 [0.01041667 0.45833333 0.35416667 0.36458333 0.47916667]
 [0.20833333 0.58333333 0.70833333 0.70833333 0.76041667]
 [0.71875    0.78125    0.44791667 0.60416667 0.66666667]
 [0.375      0.8125     0.67708333 0.35416667 0.58333333]]
